// HERE WE WILL SEE ALL OF OUR SNIPPETS IN THE SNIPPETS FOLDER.
// THERE ARE A FEW CATEGORIES TO IT, SO OPEN ONE OF THEM AND FIND OUT WHAT'S INSIDE.

package;

class Info {
	public static function print():String {
		var str:String = "HERE WE WILL SEE ALL OF OUR SNIPPETS IN THE SNIPPETS FOLDER.\nTHERE ARE A FEW CATEGORIES TO IT, SO OPEN ONE OF THEM AND FIND OUT WHAT'S INSIDE.";
		Sys.print(str);
		return str;
	}
}